# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/es89/Dropbox/Projects/Python/MultiPing_v2/ui/settings.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(361, 335)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Settings.setWindowIcon(icon)
        Settings.setSizeGripEnabled(True)
        Settings.setModal(True)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Settings)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Settings)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.defaultIp = QtWidgets.QLineEdit(self.tab)
        self.defaultIp.setObjectName("defaultIp")
        self.gridLayout_3.addWidget(self.defaultIp, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 1, 1, 1)
        self.defaultRdpLogin = QtWidgets.QLineEdit(self.tab)
        self.defaultRdpLogin.setObjectName("defaultRdpLogin")
        self.gridLayout_3.addWidget(self.defaultRdpLogin, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 1, 1, 1)
        self.defaultRdpPassword = QtWidgets.QLineEdit(self.tab)
        self.defaultRdpPassword.setObjectName("defaultRdpPassword")
        self.gridLayout_3.addWidget(self.defaultRdpPassword, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 1, 1, 1)
        self.showName = QtWidgets.QCheckBox(self.tab)
        self.showName.setObjectName("showName")
        self.gridLayout_3.addWidget(self.showName, 4, 0, 1, 1)
        self.showCount = QtWidgets.QCheckBox(self.tab)
        self.showCount.setObjectName("showCount")
        self.gridLayout_3.addWidget(self.showCount, 4, 1, 1, 1)
        self.notifyAtUp = QtWidgets.QCheckBox(self.tab)
        self.notifyAtUp.setObjectName("notifyAtUp")
        self.gridLayout_3.addWidget(self.notifyAtUp, 5, 0, 1, 1)
        self.notifyAtDown = QtWidgets.QCheckBox(self.tab)
        self.notifyAtDown.setObjectName("notifyAtDown")
        self.gridLayout_3.addWidget(self.notifyAtDown, 5, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.width = QtWidgets.QComboBox(self.tab_2)
        self.width.setEditable(True)
        self.width.setObjectName("width")
        self.width.addItem("")
        self.width.addItem("")
        self.width.addItem("")
        self.width.addItem("")
        self.width.addItem("")
        self.width.addItem("")
        self.gridLayout_2.addWidget(self.width, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.heigth = QtWidgets.QComboBox(self.tab_2)
        self.heigth.setEditable(True)
        self.heigth.setObjectName("heigth")
        self.heigth.addItem("")
        self.heigth.addItem("")
        self.heigth.addItem("")
        self.heigth.addItem("")
        self.heigth.addItem("")
        self.gridLayout_2.addWidget(self.heigth, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 1, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_4, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 1, 1, 1)
        self.fullscreen = QtWidgets.QCheckBox(self.tab_2)
        self.fullscreen.setObjectName("fullscreen")
        self.gridLayout_2.addWidget(self.fullscreen, 3, 0, 1, 1)
        self.compression = QtWidgets.QCheckBox(self.tab_2)
        self.compression.setObjectName("compression")
        self.gridLayout_2.addWidget(self.compression, 3, 1, 1, 1)
        self.audio = QtWidgets.QCheckBox(self.tab_2)
        self.audio.setObjectName("audio")
        self.gridLayout_2.addWidget(self.audio, 4, 0, 1, 1)
        self.clipboard = QtWidgets.QCheckBox(self.tab_2)
        self.clipboard.setObjectName("clipboard")
        self.gridLayout_2.addWidget(self.clipboard, 4, 1, 1, 1)
        self.themes = QtWidgets.QCheckBox(self.tab_2)
        self.themes.setObjectName("themes")
        self.gridLayout_2.addWidget(self.themes, 5, 0, 1, 1)
        self.wallpaper = QtWidgets.QCheckBox(self.tab_2)
        self.wallpaper.setObjectName("wallpaper")
        self.gridLayout_2.addWidget(self.wallpaper, 5, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 6, 0, 1, 1)
        self.pathXRDP = QtWidgets.QLineEdit(self.tab_2)
        self.pathXRDP.setObjectName("pathXRDP")
        self.gridLayout_2.addWidget(self.pathXRDP, 6, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayout = QtWidgets.QFormLayout(self.tab_3)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.colorDepthRA = QtWidgets.QComboBox(self.tab_3)
        self.colorDepthRA.setObjectName("colorDepthRA")
        self.colorDepthRA.addItem("")
        self.colorDepthRA.addItem("")
        self.colorDepthRA.addItem("")
        self.colorDepthRA.addItem("")
        self.colorDepthRA.addItem("")
        self.colorDepthRA.addItem("")
        self.gridLayout.addWidget(self.colorDepthRA, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 1, 1, 1)
        self.updates = QtWidgets.QSpinBox(self.tab_3)
        self.updates.setProperty("value", 10)
        self.updates.setObjectName("updates")
        self.gridLayout.addWidget(self.updates, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 1, 1, 1)
        self.fullscreenRA = QtWidgets.QCheckBox(self.tab_3)
        self.fullscreenRA.setText("")
        self.fullscreenRA.setObjectName("fullscreenRA")
        self.gridLayout.addWidget(self.fullscreenRA, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 4, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 4, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.gridLayout)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 331, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setHorizontalSpacing(5)
        self.formLayout_2.setObjectName("formLayout_2")
        self.browser = QtWidgets.QComboBox(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browser.sizePolicy().hasHeightForWidth())
        self.browser.setSizePolicy(sizePolicy)
        self.browser.setMinimumSize(QtCore.QSize(95, 0))
        self.browser.setEditable(True)
        self.browser.setObjectName("browser")
        self.browser.addItem("")
        self.browser.addItem("")
        self.browser.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.browser)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setMinimumSize(QtCore.QSize(220, 0))
        self.label_14.setLineWidth(2)
        self.label_14.setTextFormat(QtCore.Qt.RichText)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.midoriPath = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.midoriPath.sizePolicy().hasHeightForWidth())
        self.midoriPath.setSizePolicy(sizePolicy)
        self.midoriPath.setMinimumSize(QtCore.QSize(125, 0))
        self.midoriPath.setObjectName("midoriPath")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.midoriPath)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Dialog"))
        self.label.setText(_translate("Settings", "Default IP"))
        self.comboBox.setItemText(0, _translate("Settings", "RDP"))
        self.comboBox.setItemText(1, _translate("Settings", "RAdmin"))
        self.comboBox.setItemText(2, _translate("Settings", "IE"))
        self.label_2.setText(_translate("Settings", "Default Double-click action"))
        self.label_3.setText(_translate("Settings", "Default RDP login"))
        self.label_4.setText(_translate("Settings", "Default RDP password"))
        self.showName.setText(_translate("Settings", "Show \'NAME\' column"))
        self.showCount.setText(_translate("Settings", "Show \'COUNT\' column"))
        self.notifyAtUp.setText(_translate("Settings", "Default Notify At Up"))
        self.notifyAtDown.setText(_translate("Settings", "Default Notify At Down"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Settings", "Program settings"))
        self.width.setItemText(0, _translate("Settings", "640"))
        self.width.setItemText(1, _translate("Settings", "800"))
        self.width.setItemText(2, _translate("Settings", "1024"))
        self.width.setItemText(3, _translate("Settings", "1280"))
        self.width.setItemText(4, _translate("Settings", "1366"))
        self.width.setItemText(5, _translate("Settings", "1440"))
        self.label_5.setText(_translate("Settings", "Resolution H"))
        self.heigth.setItemText(0, _translate("Settings", "480"))
        self.heigth.setItemText(1, _translate("Settings", "600"))
        self.heigth.setItemText(2, _translate("Settings", "720"))
        self.heigth.setItemText(3, _translate("Settings", "768"))
        self.heigth.setItemText(4, _translate("Settings", "900"))
        self.label_6.setText(_translate("Settings", "Resolution V"))
        self.comboBox_4.setItemText(0, _translate("Settings", "15"))
        self.comboBox_4.setItemText(1, _translate("Settings", "16"))
        self.comboBox_4.setItemText(2, _translate("Settings", "24"))
        self.comboBox_4.setItemText(3, _translate("Settings", "32"))
        self.label_7.setText(_translate("Settings", "Color depth"))
        self.fullscreen.setText(_translate("Settings", "Fullscreen"))
        self.compression.setText(_translate("Settings", "Compression"))
        self.audio.setText(_translate("Settings", "Audio"))
        self.clipboard.setText(_translate("Settings", "Clipboard"))
        self.themes.setText(_translate("Settings", "Themes"))
        self.wallpaper.setText(_translate("Settings", "Wallpaper"))
        self.label_12.setText(_translate("Settings", "Path to XRDP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Settings", "RDP settings"))
        self.label_8.setText(_translate("Settings", "Port"))
        self.colorDepthRA.setItemText(0, _translate("Settings", "24"))
        self.colorDepthRA.setItemText(1, _translate("Settings", "16"))
        self.colorDepthRA.setItemText(2, _translate("Settings", "8"))
        self.colorDepthRA.setItemText(3, _translate("Settings", "4"))
        self.colorDepthRA.setItemText(4, _translate("Settings", "2"))
        self.colorDepthRA.setItemText(5, _translate("Settings", "1"))
        self.label_9.setText(_translate("Settings", "Color Depth"))
        self.label_10.setText(_translate("Settings", "Updates per second"))
        self.label_11.setText(_translate("Settings", "Fullscreen"))
        self.label_13.setText(_translate("Settings", "Path to radmin.exe"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Settings", "RAdmin settings"))
        self.browser.setItemText(0, _translate("Settings", "internal"))
        self.browser.setItemText(1, _translate("Settings", "midori"))
        self.browser.setItemText(2, _translate("Settings", "firefox"))
        self.label_14.setText(_translate("Settings", " Browser (must be accessable in console)"))
        self.label_15.setText(_translate("Settings", "path to midori.exe"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Settings", "IE settings"))

import ui.icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings = QtWidgets.QDialog()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec_())

